services:
  - type: web
    name: todo-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: todo_project.settings
      - key: PYTHON_VERSION
        value: 3.11
